development:
  adapter: postgresql
  encoding: unicode
  database: texter_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: texter_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: texter_production
  pool: 5
